const test=require("node:test"),assert=require("node:assert/strict"),path=require("node:path"),crypto=require("node:crypto");
require(path.resolve(__dirname,"../tilda/dilivox-event-layer-task006.js"));
const E=globalThis.ProfitEngineEvents;
function agent(type="story"){return {health:{state:"READY"},experiment:{experiment_id:"exp",variant_id:"v1"},getContext:()=>({schema_version:"1.0",site_id:"dilivox",session_ref:"session",content_id:"content",page_type:type,acquisition_ref:"acq",cohort_ref:"cohort",experiment_id:"exp",variant_id:"v1",return_ref:"return"})};}
function win(){return {crypto:{randomUUID:()=>crypto.randomUUID()},__PROFIT_ENGINE_EVENT_DISPATCH_DISABLED__:false};}
test("taxonomy exact and text/comic page singleton",()=>{assert.equal(E.TYPES.size,16);for(const type of ["story","comic"]){const c=new E.Controller(win(),agent(type),{});c.pageLoad(true);c.pageLoad(true);assert.deepEqual(c.queue.items.map(x=>x.event.event_type),["page_view_site","story_open"]);}});
test("content-relative geometry emits 25 50 75 once",()=>{const c=new E.Controller(win(),agent(),{});assert.equal(c.progressFromGeometry({top:500,height:1000},1000),.5);c.progressFromGeometry({top:0,height:1000},1000);c.progressFromGeometry({top:0,height:1000},1000);assert.deepEqual(c.queue.items.map(x=>x.event.event_type),["story_progress_25","story_progress_50","story_progress_75"]);});
test("choice visibility trusted selection excludes answer text",()=>{const c=new E.Controller(win(),agent(),{});c.choiceSectionVisible(.2);c.choiceSectionVisible(.5);c.selectChoice(2,true,false);c.selectChoice(2,true,true);const events=c.queue.items.map(x=>x.event);assert.equal(events[0].event_type,"version_section_seen");assert.deepEqual(events[1].properties,{choice_ref:"2",is_correct:true});assert.equal(JSON.stringify(events).includes("answer"),false);});
test("reveal differs from completion and requires genuine view",()=>{const c=new E.Controller(win(),agent(),{});c.selectChoice(1,false,true);c.reveal(true,.1);assert.equal(c.queue.items.at(-1).event.event_type,"reveal_opened");c.reveal(true,.5);assert.equal(c.queue.items.at(-1).event.event_type,"story_completed");});
test("navigation stable IDs catalog return exposure and approved conversion",()=>{const c=new E.Controller(win(),agent(),{});c.nextSeen("dest",.5);c.nextClicked("dest",true);c.catalog(true);c.returnVisit();c.exposure(true);c.conversion({approved:false,source_event_id:"x",conversion_key:"k"});c.conversion({approved:true,source_event_id:"x",conversion_key:"k"});const es=c.queue.items.map(x=>x.event);assert.equal(es[1].destination_content_id,"dest");assert.deepEqual(es.map(x=>x.event_type),["next_story_seen","next_story_clicked","catalog_opened","return_visit","experiment_exposure","experiment_conversion"]);});
test("idempotency deterministic while event_id random",()=>{const a=new E.Builder(win(),agent(),{created:0,duplicates:0,rejected:0,instrumentation_errors:0,unresolved_content_identity:0});const b=new E.Builder(win(),agent(),{created:0,duplicates:0,rejected:0,instrumentation_errors:0,unresolved_content_identity:0});const x=a.create("story_open","one"),y=b.create("story_open","one");assert.equal(x.idempotency_key,y.idempotency_key);assert.notEqual(x.event_id,y.event_id);});
test("queue cap overflow TTL and bounded retry",async()=>{let now=0,calls=0;const h={dropped:0,overflow:0,queue_depth:0,sent:0,acked:0,delivery_failures:0};const q=new E.Queue({now:()=>now,transport:async()=>{calls++;return calls===3;}},h);for(let i=0;i<51;i++)q.push({i});assert.equal(q.items.length,50);assert.equal(h.overflow,1);const result=await q.flush();assert.deepEqual(result,{status:"acked",attempts:3});assert.equal(calls,3);q.push({late:true});now=E.TTL+1;q.prune();assert.equal(q.items.length,0);});
test("transport exception and dispatch kill fail open",async()=>{const h={dropped:0,overflow:0,queue_depth:0,sent:0,acked:0,delivery_failures:0};const q=new E.Queue({transport:async()=>{throw Error("offline")}},h);q.push({safe:true});assert.equal((await q.flush()).status,"failed");assert.equal(h.delivery_failures,3);const c=new E.Controller(win(),agent(),{dispatchKillSwitch:true});assert.equal(c.emit("page_view_site","p"),null);});
test("privacy-minimal health/performance and no provider money semantics",()=>{const c=new E.Controller(win(),agent(),{});c.recordError("TypeError","redacted-class");c.recordPerformance({navigation_ms:123.4,lcp_ms:456.7,cls:.12,long_task_count:2});assert.equal("stack" in c.health,false);assert.equal("url" in c.health,false);assert.equal(c.health.last_error_signature.startsWith("err_"),true);assert.equal(c.health.lcp_ms,457);assert.equal([...E.TYPES].some(x=>/impression|revenue/i.test(x)),false);});
test("mobile and desktop use identical semantic controller",()=>{for(const width of [390,1440]){const c=new E.Controller(win(),agent(),{});c.pageLoad(true);c.progress(.75);assert.equal(c.queue.items.length,5);}});
test("bundle has no production endpoint, sync XHR, or YAN mutation",()=>{const s=require("node:fs").readFileSync(path.resolve(__dirname,"../tilda/dilivox-event-layer-task006.js"),"utf8");assert.equal(/https?:\/\//.test(s),false);for(const x of ["XMLHttpRequest","Ya.Context","renderTo("])assert.equal(s.includes(x),false);});
